# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dynatrace-eks-cluster
  region: ap-south-1
  version: "1.31"

managedNodeGroups:
  - name: ng-demo
    instanceType: t3.xlarge
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    privateNetworking: true
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        # ebs: true attaches AmazonEBSCSIDriverPolicy to node IAM role

addons:
  - name: vpc-cni
    version: latest

  - name: coredns
    version: latest

  - name: kube-proxy
    version: latest

  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies:
      ebsCSIController: true