apiVersion: v1
data:
  apiToken: ZHQwYzAxLlJKS0JLNFZOTzNZMlZXSTNKNFU1U1FRVi5DNUhFUzJUVDRJQlpENzJORzJCN05DT0w0NEZBNlQ2SlhEWllPNEcyNUhaR0U1WVpGVFZITlA1TjZJMkdRRkxH
  dataIngestToken: ZHQwYzAxLjc3UUlKNDdKN0dZNlFUNzVXREM3SFhQRi5CN0hWUlZJR0ZPR1VWSUFWUUNZNVQ1SzRIWUhVVTRIQzM1Rk9DQ1dPVFVITlFJSU81WlFJSVBWMkZZWlZRUzMz
kind: Secret
metadata:
  name: dynatrace-eks-cluster
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
type: Opaque
---
apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: dynatrace-eks-cluster
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://bhs57423.live.dynatrace.com/api
  tokens: dynatrace-eks-cluster
  activeGate:
    capabilities:
      - kubernetes-monitoring
    resources:
      requests:
        cpu: 200m
        memory: 6Gi
      limits:
        cpu: 1000m
        memory: 6Gi
    replicas: 1
---
apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: dynatrace-eks-cluster-agents
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://bhs57423.live.dynatrace.com/api
  tokens: dynatrace-eks-cluster
  metadataEnrichment:
    enabled: true
  oneAgent:
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  activeGate:
    capabilities:
      - routing
      - debugging
    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    replicas: 1
  templates:
    otelCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-otel-collector
        tag: latest
  logMonitoring: {}
  telemetryIngest:
    protocols:
      - jaeger
      - otlp
      - statsd
      - zipkin
    serviceName: telemetry-ingest
