# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dynatrace-eks-app-service
spec:
  type: LoadBalancer
  selector:
    app: dynatrace-eks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000